title: Francis Davey
description: My personal legal blog
url: "https://francisdavey.github.io/tech-law-blog"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: "Francis Davey"
